-- ============================================================
-- DB2 TARGET SCHEMA
-- Auto-generated from table_mappings.json
-- ============================================================

-- Table: PRODUCTS
CREATE TABLE PRODUCTS (
    PRODUCT_ID DECIMAL(10,0) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10,2),
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID)
);


-- Table: CUSTOMERS
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID DECIMAL(10,0) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20),
    REGISTRATION_DATE TIMESTAMP NOT NULL,
    LOYALTY_POINTS DECIMAL(10,0),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);


-- Table: ORDERS
CREATE TABLE ORDERS (
    ORDER_ID DECIMAL(10,0) NOT NULL,
    CUSTOMER_ID DECIMAL(10,0) NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL,
    ORDER_STATUS VARCHAR(20) NOT NULL,
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
    SHIPPING_ADDRESS VARCHAR(500),
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID)
);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_CUSTOMER_ID
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID);

CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON ORDERS(CUSTOMER_ID);

-- Table: ORDER_ITEMS
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID DECIMAL(10,0) NOT NULL,
    ORDER_ID DECIMAL(10,0) NOT NULL,
    PRODUCT_ID DECIMAL(10,0) NOT NULL,
    QUANTITY DECIMAL(5,0) NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    DISCOUNT_PERCENT DECIMAL(5,2),
    LINE_TOTAL DECIMAL(12,2) NOT NULL,
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ITEM_ID)
);

ALTER TABLE ORDER_ITEMS
    ADD CONSTRAINT FK_ORDER_ITEMS_ORDER_ID
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS(ORDER_ID);

ALTER TABLE ORDER_ITEMS
    ADD CONSTRAINT FK_ORDER_ITEMS_PRODUCT_ID
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID);

CREATE INDEX IDX_ORDER_ITEMS_ORDER_ID ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_ORDER_ITEMS_PRODUCT_ID ON ORDER_ITEMS(PRODUCT_ID);

-- Table: SYNERGIES
CREATE TABLE SYNERGIES (
    SYNERGY_ID DECIMAL(10,0) NOT NULL,
    PRODUCT_ID_1 DECIMAL(10,0) NOT NULL,
    PRODUCT_ID_2 DECIMAL(10,0) NOT NULL,
    SYNERGY_SCORE DECIMAL(5,2) NOT NULL,
    CONSTRAINT PK_SYNERGIES PRIMARY KEY (SYNERGY_ID)
);

ALTER TABLE SYNERGIES
    ADD CONSTRAINT FK_SYNERGIES_PRODUCT_ID_1
    FOREIGN KEY (PRODUCT_ID_1)
    REFERENCES PRODUCTS(PRODUCT_ID);

ALTER TABLE SYNERGIES
    ADD CONSTRAINT FK_SYNERGIES_PRODUCT_ID_2
    FOREIGN KEY (PRODUCT_ID_2)
    REFERENCES PRODUCTS(PRODUCT_ID);

CREATE INDEX IDX_SYNERGIES_PRODUCT_ID_1 ON SYNERGIES(PRODUCT_ID_1);
CREATE INDEX IDX_SYNERGIES_PRODUCT_ID_2 ON SYNERGIES(PRODUCT_ID_2);

-- Table: DATATYPE_TEST
CREATE TABLE DATATYPE_TEST (
    TEST_ID DECIMAL(10,0) NOT NULL,
    NUM_INTEGER INTEGER,
    NUM_SMALLINT SMALLINT,
    NUM_DECIMAL DECIMAL(15,4),
    NUM_FLOAT DOUBLE,
    CHAR_FIXED CHAR(10),
    CHAR_VAR VARCHAR(100),
    DATE_FIELD TIMESTAMP,
    TIMESTAMP_FIELD TIMESTAMP,
    CLOB_FIELD CLOB,
    BLOB_FIELD BLOB,
    CONSTRAINT PK_DATATYPE_TEST PRIMARY KEY (TEST_ID)
);


-- Table: ORACLE_DATATYPE_COMPREHENSIVE
CREATE TABLE ORACLE_DATATYPE_COMPREHENSIVE (
    ID DECIMAL(10,0) NOT NULL,
    NUM_NO_PRECISION DECIMAL(31,0),
    NUM_WITH_PRECISION DECIMAL(10,0),
    NUM_WITH_SCALE DECIMAL(10,2),
    INT_TYPE INTEGER,
    SMALLINT_TYPE SMALLINT,
    FLOAT_TYPE DOUBLE,
    FLOAT_WITH_PRECISION DOUBLE,
    BINARY_FLOAT_TYPE REAL,
    BINARY_DOUBLE_TYPE DOUBLE,
    CHAR_TYPE CHAR(50),
    VARCHAR_TYPE VARCHAR(100),
    VARCHAR2_TYPE VARCHAR(200),
    NCHAR_TYPE GRAPHIC(25),
    NVARCHAR2_TYPE VARGRAPHIC(100),
    DATE_TYPE TIMESTAMP,
    TIMESTAMP_TYPE TIMESTAMP,
    TIMESTAMP_PRECISION TIMESTAMP(6),
    TIMESTAMP_TZ TIMESTAMP,
    TIMESTAMP_LTZ TIMESTAMP,
    INTERVAL_YM VARCHAR(30),
    INTERVAL_DS VARCHAR(30),
    RAW_TYPE VARCHAR(100) FOR BIT DATA,
    CLOB_TYPE CLOB,
    NCLOB_TYPE DBCLOB,
    BLOB_TYPE BLOB,
    ROWID_TYPE VARCHAR(18),
    UROWID_TYPE VARCHAR(4000),
    CONSTRAINT PK_ORACLE_DATATYPE_COMPREHENSIVE PRIMARY KEY (ID)
);

