-- ============================================================
-- ORACLE SOURCE SCHEMA
-- Auto-generated from table_mappings.json
-- ============================================================

-- Table: PRODUCTS
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER(10) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    PRICE NUMBER(10,2),
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID)
);


-- Table: CUSTOMERS
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(10) NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    PHONE VARCHAR2(20),
    REGISTRATION_DATE DATE NOT NULL,
    LOYALTY_POINTS NUMBER(10),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);


-- Table: ORDERS
CREATE TABLE ORDERS (
    ORDER_ID NUMBER(10) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR2(20) NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    SHIPPING_ADDRESS VARCHAR2(500),
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID)
);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_CUSTOMER_ID
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID);

CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON ORDERS(CUSTOMER_ID);

-- Table: ORDER_ITEMS
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER(10) NOT NULL,
    ORDER_ID NUMBER(10) NOT NULL,
    PRODUCT_ID NUMBER(10) NOT NULL,
    QUANTITY NUMBER(5) NOT NULL,
    UNIT_PRICE NUMBER(10,2) NOT NULL,
    DISCOUNT_PERCENT NUMBER(5,2),
    LINE_TOTAL NUMBER(12,2) NOT NULL,
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ITEM_ID)
);

ALTER TABLE ORDER_ITEMS
    ADD CONSTRAINT FK_ORDER_ITEMS_ORDER_ID
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS(ORDER_ID);

ALTER TABLE ORDER_ITEMS
    ADD CONSTRAINT FK_ORDER_ITEMS_PRODUCT_ID
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID);

CREATE INDEX IDX_ORDER_ITEMS_ORDER_ID ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_ORDER_ITEMS_PRODUCT_ID ON ORDER_ITEMS(PRODUCT_ID);

-- Table: SYNERGIES
CREATE TABLE SYNERGIES (
    SYNERGY_ID NUMBER(10) NOT NULL,
    PRODUCT_ID_1 NUMBER(10) NOT NULL,
    PRODUCT_ID_2 NUMBER(10) NOT NULL,
    SYNERGY_SCORE NUMBER(5,2) NOT NULL,
    CONSTRAINT PK_SYNERGIES PRIMARY KEY (SYNERGY_ID)
);

ALTER TABLE SYNERGIES
    ADD CONSTRAINT FK_SYNERGIES_PRODUCT_ID_1
    FOREIGN KEY (PRODUCT_ID_1)
    REFERENCES PRODUCTS(PRODUCT_ID);

ALTER TABLE SYNERGIES
    ADD CONSTRAINT FK_SYNERGIES_PRODUCT_ID_2
    FOREIGN KEY (PRODUCT_ID_2)
    REFERENCES PRODUCTS(PRODUCT_ID);

CREATE INDEX IDX_SYNERGIES_PRODUCT_ID_1 ON SYNERGIES(PRODUCT_ID_1);
CREATE INDEX IDX_SYNERGIES_PRODUCT_ID_2 ON SYNERGIES(PRODUCT_ID_2);

-- Table: DATATYPE_TEST
CREATE TABLE DATATYPE_TEST (
    TEST_ID NUMBER(10) NOT NULL,
    NUM_INTEGER INTEGER,
    NUM_SMALLINT SMALLINT,
    NUM_DECIMAL NUMBER(15,4),
    NUM_FLOAT FLOAT,
    CHAR_FIXED CHAR(10),
    CHAR_VAR VARCHAR2(100),
    DATE_FIELD DATE,
    DATE_FIELD DATE,
    CLOB_FIELD CLOB,
    BLOB_FIELD BLOB,
    CONSTRAINT PK_DATATYPE_TEST PRIMARY KEY (TEST_ID)
);


-- Table: ORACLE_DATATYPE_COMPREHENSIVE
CREATE TABLE ORACLE_DATATYPE_COMPREHENSIVE (
    ID NUMBER(10) NOT NULL,
    NUM_NO_PRECISION NUMBER,
    NUM_WITH_PRECISION NUMBER(10),
    NUM_WITH_SCALE NUMBER(10,2),
    INT_TYPE INTEGER,
    SMALLINT_TYPE SMALLINT,
    FLOAT_TYPE FLOAT,
    FLOAT_WITH_PRECISION FLOAT,
    BINARY_FLOAT_TYPE BINARY_FLOAT,
    BINARY_DOUBLE_TYPE FLOAT,
    CHAR_TYPE CHAR(50),
    VARCHAR_TYPE VARCHAR(100),
    VARCHAR2_TYPE VARCHAR2(200),
    NCHAR_TYPE NCHAR(25),
    NVARCHAR2_TYPE NVARCHAR2(100),
    DATE_TYPE DATE,
    DATE_TYPE DATE,
    DATE_PRECISION DATE(6),
    DATE_TZ DATE,
    DATE_LTZ DATE,
    INTERVAL_YM INTERVAL YEAR TO MONTH,
    INTERVAL_DS INTERVAL YEAR TO MONTH,
    RAW_TYPE RAW(100),
    CLOB_TYPE CLOB,
    NCLOB_TYPE NCLOB,
    BLOB_TYPE BLOB,
    ROWID_TYPE ROWID,
    UROWID_TYPE UROWID,
    CONSTRAINT PK_ORACLE_DATATYPE_COMPREHENSIVE PRIMARY KEY (ID)
);

